#!/usr/bin/env python3
"""
LocalChat Setup Script
======================
Checks prerequisites and configures the environment for a fresh install.
Works on Linux, macOS, and Windows.

Usage:
    python install.py
"""

import sys
import os
import subprocess
import secrets
import json
import getpass
import urllib.request
import urllib.error
from pathlib import Path

# ---------------------------------------------------------------------------
# Minimum requirements
# ---------------------------------------------------------------------------

MIN_PYTHON = (3, 10)
PGVECTOR_IMAGE = "pgvector/pgvector:pg16"
POSTGRES_CONTAINER = "localchat-postgres"

# ---------------------------------------------------------------------------
# Terminal colours  (ANSI — enabled on Windows 10+ via os.system(""))
# ---------------------------------------------------------------------------

if sys.platform == "win32":
    os.system("")

G = "\033[92m"   # green
Y = "\033[93m"   # yellow
R = "\033[91m"   # red
C = "\033[96m"   # cyan
B = "\033[1m"    # bold
X = "\033[0m"    # reset

def _ok(msg: str)   -> None: print(f"  {G}ok{X}    {msg}")
def _warn(msg: str) -> None: print(f"  {Y}warn{X}  {msg}")
def _fail(msg: str) -> None: print(f"  {R}fail{X}  {msg}")
def _info(msg: str) -> None: print(f"  {C}    {X}  {msg}")
def _head(msg: str) -> None: print(f"\n{B}{C}{msg}{X}")
def _step(msg: str) -> None: print(f"\n{B}{msg}{X}")

# ---------------------------------------------------------------------------
# Prerequisite checks
# ---------------------------------------------------------------------------

def check_python() -> bool:
    v = sys.version_info
    label = f"Python {v.major}.{v.minor}.{v.micro}"
    if v >= MIN_PYTHON:
        _ok(label)
        return True
    _fail(f"{label}  --  {MIN_PYTHON[0]}.{MIN_PYTHON[1]}+ required")
    return False


def _run(cmd: list) -> tuple:
    """Run a subprocess. Returns (success: bool, stdout_first_line: str)."""
    try:
        r = subprocess.run(cmd, capture_output=True, text=True, timeout=10)
        first = (r.stdout.strip().splitlines() or [""])[0]
        return r.returncode == 0, first
    except (FileNotFoundError, subprocess.TimeoutExpired):
        return False, ""


def check_docker() -> bool:
    found, ver = _run(["docker", "--version"])
    if found:
        _ok(ver)
        return True
    _warn("Docker not found  --  PostgreSQL will need manual setup")
    _info("https://docs.docker.com/get-docker/")
    return False


def check_ollama() -> bool:
    # Try CLI
    found, ver = _run(["ollama", "--version"])
    if found:
        _ok(f"Ollama  ({ver})")
        return True
    # Try HTTP (running but not in PATH)
    try:
        with urllib.request.urlopen("http://localhost:11434/api/version", timeout=3) as r:
            data = json.loads(r.read())
            _ok(f"Ollama API  (v{data.get('version', '?')})")
            return True
    except Exception:
        pass
    _warn("Ollama not found  --  required for LLM and embeddings")
    _info("https://ollama.ai")
    return False

# ---------------------------------------------------------------------------
# Interactive prompts
# ---------------------------------------------------------------------------

def ask(prompt: str, default: str = "", hidden: bool = False) -> str:
    hint = f"[{default}] " if default else ""
    display = f"  {C}{prompt}{X} {hint}: "
    while True:
        val = (getpass.getpass(display) if hidden else input(display)).strip()
        if val:
            return val
        if default:
            return default
        print(f"  {R}Required.{X}")


def ask_bool(prompt: str, default: bool = True) -> bool:
    hint = "Y/n" if default else "y/N"
    val = input(f"  {C}{prompt}{X} [{hint}]: ").strip().lower()
    return default if not val else val in ("y", "yes")

# ---------------------------------------------------------------------------
# .env template & writer
# ---------------------------------------------------------------------------

_ENV = """\
# LocalChat — generated by install.py  (do not commit)

# Application
APP_NAME=LocalChat
APP_ENV={app_env}
DEBUG={debug}
SECRET_KEY={secret_key}
HOST={host}
PORT={port}

# Security
JWT_SECRET_KEY={jwt_secret}
JWT_ACCESS_TOKEN_EXPIRES=3600
ADMIN_PASSWORD={admin_password}
RATELIMIT_ENABLED=True
RATELIMIT_CHAT=10 per minute
RATELIMIT_UPLOAD=5 per hour
RATELIMIT_MODELS=20 per minute
RATELIMIT_GENERAL=60 per minute
CORS_ENABLED=False
CORS_ORIGINS=http://localhost:{port}

# Database
PG_HOST={pg_host}
PG_PORT={pg_port}
PG_USER={pg_user}
PG_PASSWORD={pg_password}
PG_DB={pg_db}
DB_POOL_MIN_CONN=2
DB_POOL_MAX_CONN=10
DB_POOL_TIMEOUT=5

# Ollama
OLLAMA_BASE_URL={ollama_url}
OLLAMA_TIMEOUT=120
OLLAMA_DEFAULT_MODEL={chat_model}
OLLAMA_EMBEDDING_MODEL={embed_model}

# RAG
CHUNK_SIZE=768
CHUNK_OVERLAP=128
TOP_K_RESULTS=15
MIN_SIMILARITY_THRESHOLD=0.25
RERANK_RESULTS=True
MAX_WORKERS=4
MAX_UPLOAD_SIZE_MB=16
DEFAULT_TEMPERATURE=0.0
MAX_CONTEXT_LENGTH=6000
STREAM_RESPONSES=True

# Uploads / Logging
UPLOAD_FOLDER=uploads
ALLOWED_EXTENSIONS=.pdf,.txt,.docx,.md
MAX_FILE_SIZE=16777216
LOG_LEVEL={log_level}
LOG_FILE=logs/app.log
LOG_MAX_SIZE=10485760
LOG_BACKUP_COUNT=5

# Redis (optional)
REDIS_ENABLED={redis_enabled}
REDIS_HOST={redis_host}
REDIS_PORT={redis_port}
REDIS_DB=0
REDIS_PASSWORD={redis_password}
"""


def write_env(cfg: dict) -> None:
    Path(".env").write_text(_ENV.format(**cfg), encoding="utf-8")
    _ok(f"Written  {Path('.env').resolve()}")


def collect_env(docker_ok: bool) -> dict:
    print()
    app_env = ask("Environment", "development")
    is_dev  = app_env.startswith("dev")

    secret_key = secrets.token_urlsafe(32)
    jwt_secret = secrets.token_urlsafe(32)
    _info("SECRET_KEY and JWT_SECRET_KEY generated automatically.")

    admin_password = ask("Admin password  (/api/auth/login)", hidden=True)
    host = ask("Server host", "localhost")
    port = ask("Server port", "5000")

    print()
    pg_host     = ask("PostgreSQL host", "localhost")
    pg_port     = ask("PostgreSQL port", "5432")
    pg_user     = ask("PostgreSQL user", "postgres")
    pg_password = ask("PostgreSQL password", hidden=True)
    pg_db       = ask("PostgreSQL database", "rag_db")

    print()
    ollama_url  = ask("Ollama URL",        "http://localhost:11434")
    chat_model  = ask("Chat model",        "llama3.1:latest")
    embed_model = ask("Embedding model",   "nomic-embed-text:latest")

    print()
    redis_enabled  = ask_bool("Enable Redis cache?", default=False)
    redis_host, redis_port_r, redis_password = "localhost", "6379", ""
    if redis_enabled:
        redis_host     = ask("Redis host", "localhost")
        redis_port_r   = ask("Redis port", "6379")
        redis_password = ask("Redis password  (blank = none)", "")

    return dict(
        app_env=app_env,
        debug="True" if is_dev else "False",
        log_level="DEBUG" if is_dev else "INFO",
        secret_key=secret_key,
        jwt_secret=jwt_secret,
        admin_password=admin_password,
        host=host,
        port=port,
        pg_host=pg_host,
        pg_port=pg_port,
        pg_user=pg_user,
        pg_password=pg_password,
        pg_db=pg_db,
        ollama_url=ollama_url,
        chat_model=chat_model,
        embed_model=embed_model,
        redis_enabled=str(redis_enabled),
        redis_host=redis_host,
        redis_port=redis_port_r,
        redis_password=redis_password,
    )

# ---------------------------------------------------------------------------
# Docker PostgreSQL helper
# ---------------------------------------------------------------------------

def _docker(cmd: list, timeout: int = 30) -> tuple:
    """Run a docker subcommand. Returns (success, stdout, stderr)."""
    try:
        r = subprocess.run(
            ["docker"] + cmd,
            capture_output=True, text=True, timeout=timeout,
        )
        return r.returncode == 0, r.stdout.strip(), r.stderr.strip()
    except FileNotFoundError:
        return False, "", "docker not found"
    except subprocess.TimeoutExpired:
        return False, "", f"timed out after {timeout}s"


def start_postgres(user: str, password: str, db: str, port: str) -> None:
    # Check if the container already exists (running OR stopped)
    ok, names, _ = _docker([
        "ps", "-a",
        "--filter", f"name={POSTGRES_CONTAINER}",
        "--format", "{{.Names}}",
    ])
    existing = [n for n in names.splitlines() if n == POSTGRES_CONTAINER]

    if existing:
        # Container exists — check if it is running
        ok, state, _ = _docker([
            "inspect", "--format", "{{.State.Status}}", POSTGRES_CONTAINER,
        ])
        if state == "running":
            _ok(f"Container '{POSTGRES_CONTAINER}' is already running.")
            return
        # Stopped — just start it
        _info(f"Container '{POSTGRES_CONTAINER}' exists but is stopped — starting it.")
        ok, _, err = _docker(["start", POSTGRES_CONTAINER])
        if ok:
            _ok(f"Container '{POSTGRES_CONTAINER}' started.")
        else:
            _fail(f"docker start failed: {err}")
        return

    # Pull image (already cached after first run — docker is smart about this)
    print(f"  Pulling {PGVECTOR_IMAGE} ...")
    subprocess.run(["docker", "pull", PGVECTOR_IMAGE], check=False)

    run_ok, _, err = _docker([
        "run", "-d",
        "--name", POSTGRES_CONTAINER,
        "-e", f"POSTGRES_USER={user}",
        "-e", f"POSTGRES_PASSWORD={password}",
        "-e", f"POSTGRES_DB={db}",
        "-p", f"{port}:5432",
        "--restart", "unless-stopped",
        PGVECTOR_IMAGE,
    ], timeout=60)

    if run_ok:
        _ok(f"Container '{POSTGRES_CONTAINER}' started on port {port}.")
        _info("PostgreSQL will be ready in a few seconds.")
        return

    # Diagnose common failure modes
    err_lower = err.lower()
    if "port is already allocated" in err_lower or "address already in use" in err_lower:
        _fail(f"Port {port} is already in use.")
        _info("A PostgreSQL instance may already be running on this machine.")
        _info(f"Change PG_PORT in .env or stop the process using port {port}.")
    elif "conflict" in err_lower and "name" in err_lower:
        _fail("Container name conflict (unexpected — please run: docker rm localchat-postgres)")
    else:
        _fail(f"docker run failed: {err or '(no error output)'}")

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def create_dirs() -> None:
    for d in ("uploads", "logs"):
        Path(d).mkdir(exist_ok=True)
    Path("uploads/.gitkeep").touch(exist_ok=True)
    _ok("Directories: uploads/  logs/")


def install_deps() -> None:
    print("  Running pip install -r requirements.txt ...")
    r = subprocess.run(
        [sys.executable, "-m", "pip", "install", "-r", "requirements.txt"]
    )
    if r.returncode == 0:
        _ok("Dependencies installed.")
    else:
        _fail("pip install failed — run  pip install -r requirements.txt  manually.")


def load_env_file() -> dict:
    """Parse .env into a plain dict (no external deps needed)."""
    result: dict = {}
    try:
        for line in Path(".env").read_text(encoding="utf-8").splitlines():
            line = line.strip()
            if line and not line.startswith("#") and "=" in line:
                k, _, v = line.partition("=")
                result[k.strip()] = v.strip()
    except FileNotFoundError:
        pass
    return result


def pull_model(model: str) -> None:
    print(f"  Pulling {model} ...")
    subprocess.run(["ollama", "pull", model], check=False)

# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main() -> None:
    _head("=" * 54)
    _head("  LocalChat  --  environment setup")
    _head("=" * 54)

    # ── 1. Prerequisites ───────────────────────────────────
    _step("[1/3]  Checking prerequisites")
    py_ok     = check_python()
    docker_ok = check_docker()
    ollama_ok = check_ollama()

    if not py_ok:
        print(f"\n{R}Python {MIN_PYTHON[0]}.{MIN_PYTHON[1]}+ is required. Aborting.{X}\n")
        sys.exit(1)

    # ── 2. Configure .env ──────────────────────────────────
    _step("[2/3]  Configure environment  (.env)")
    env_path = Path(".env")
    if env_path.exists():
        if ask_bool(".env already exists — overwrite?", default=False):
            write_env(collect_env(docker_ok))
        else:
            _info("Keeping existing .env.")
    else:
        write_env(collect_env(docker_ok))

    # ── 3. Finalise ────────────────────────────────────────
    _step("[3/3]  Finalising")
    create_dirs()

    if ask_bool("Install Python dependencies?", default=True):
        install_deps()

    if docker_ok and ask_bool("Start PostgreSQL + pgvector via Docker?", default=True):
        cfg = load_env_file()
        start_postgres(
            cfg.get("PG_USER", "postgres"),
            cfg.get("PG_PASSWORD", ""),
            cfg.get("PG_DB", "rag_db"),
            cfg.get("PG_PORT", "5432"),
        )

    if ollama_ok:
        cfg = load_env_file()
        chat  = cfg.get("OLLAMA_DEFAULT_MODEL",   "llama3.1:latest")
        embed = cfg.get("OLLAMA_EMBEDDING_MODEL", "nomic-embed-text:latest")
        if ask_bool(f"Pull chat model  ({chat})?", default=False):
            pull_model(chat)
        if ask_bool(f"Pull embedding model  ({embed})?", default=False):
            pull_model(embed)

    # ── Done ───────────────────────────────────────────────
    _head("\nSetup complete.")
    print(f"\n  Start the app:  {B}python app.py{X}")
    print(f"  Open browser:   {B}http://localhost:5000{X}\n")


if __name__ == "__main__":
    main()
